author:
  name: Cam Wallace
  role: Longevity Biology Ops & Finance
  bio:  Lorem Ipsum
  location: Cambridge, UK

social:
  - id: "linkedin"
    label: "Linkedin"
    href: "https://www.linkedin.com/in/cameronjameswallace/"
  - id: "email"
    label: "Email"
    href: "mailto:camcoenzyme@gmail.com"
